version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafka-network

  helloservice:
    container_name: helloservice
    build:
      context: ./helloservice 
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - api
    networks:
      - kafka-network
  
  ordermanager:
    container_name: ordermanager
    build:
      context: ./ordermanager 
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - api
    networks:
      - kafka-network


  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - 3000:3000
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: SuperSecurePassword2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  kafka-network:
    driver: bridge